environment: 'localhost'
host: 0.0.0.0
port: 3500
version: '1.0.0'

dbConfigurationProduct:
  host: 'localhost'
  port: 5433
  username: 'admin'
  password: '123456'
  database: 'poc-db'
  synchronize: false
  ssl: { enabled: false, rejectUnauthorized: false }
  rejectUnauthorized: false
